### PR TITLE
Changes for Beat Saber 1.37.1

### PR DESCRIPTION
**Pull request by qqrz997**
### Notes:
1.34.4 introduced a new beatmap model but everything needed is still there. Mappers and lighters are separate lists which currently aren't used because BeatSaver is yet to support v4 beatmaps, and these aren't parsed/displayed anywhere within the game so there's no defined way to display v4 beatmap authors. Taking the first of the list should work just fine for anything before v4.

It seems that the percentage score result calculation is sometimes off however I wasn't able to consistently reproduce. Sometimes it would show a percentage greater than 100%.

### CODE REVIEW

**Comment by qqrz997** [comment]
i don't know if you're still maintaining this mod because i know the website for the data is down. i am however a fan of the results screen UI this provides and would be nice to keep around. BeatLeader saves almost identical data to this so having a website for BeatSaviorData isn't really necessary at this point, i would say.

**Comment by zaourzag** [comment]
hiya! do you have the compiled file for this? I've been trying to compile this but it wont compile. so i give up, could you send over a compiled version?

**Comment by qqrz997** [comment]
no, what you should do is get the BeatSaberModdingTools.Tasks NuGet package in visual studio (there is a rider version), use it to set your beat saber directory, and it will generate a csproj.user that will sort out the reference paths

**Comment by qqrz997** [comment]
just updated the PR with changes for 1.37.5. the main change is that BSML requires the menu scene to be loaded before adding menus now.

**Pull request merged**
